# Site settings
title: HyeongJunYoo
description: Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyeongjunyoo.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HyeongJunYoo
user_description: 유형준의 포트폴리오
user_title: 유형준의 포트폴리오
email: yoojoo97@gmail.com
# twitter_username: lorem_ipsum
instagram_username: 인스타그램
facebook_username: 페이스북
linkedin_username: 링크인
github_username:  깃허브
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

